"""
api/main.py — Phase 5
FastAPI application that exposes the RAG pipeline as an HTTP API.

Run from the project root:
    uvicorn api.main:app --reload

Interactive docs (auto-generated by FastAPI):
    http://127.0.0.1:8000/docs
"""

from __future__ import annotations

import logging
from contextlib import asynccontextmanager
from typing import Callable

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# PYDANTIC MODELS — define the exact shape of every request and response.
# FastAPI reads these to validate incoming JSON and to generate /docs.
# ─────────────────────────────────────────────────────────────────────────────

class QueryRequest(BaseModel):
    """Body sent by the caller to POST /query."""

    question: str = Field(
        ...,
        description="A clinical question about breast cancer treatment.",
        min_length=1,
        examples=["What are first-line treatments for HER2-positive breast cancer?"],
    )
    k: int = Field(
        5,
        description="How many PubMed abstracts to retrieve as context (1–20).",
        ge=1,
        le=20,
    )


class Source(BaseModel):
    """One retrieved PubMed abstract used as RAG context."""

    pmid: str = Field(..., description="PubMed identifier — use to build a link to pubmed.ncbi.nlm.nih.gov")
    title: str = Field(..., description="Article title.")
    snippet: str = Field(..., description="First ~300 characters of the abstract.")


class QueryResponse(BaseModel):
    """Full response returned by POST /query."""

    answer: str = Field(
        ...,
        description="Gemini-generated answer with inline [PMID: XXXXXXXX] citations.",
    )
    sources: list[Source] = Field(
        ...,
        description="The k retrieved abstracts that grounded the answer.",
    )


class HealthResponse(BaseModel):
    status: str


# ─────────────────────────────────────────────────────────────────────────────
# STARTUP — load the embedding model and Chroma index ONCE.
#
# Why lifespan, not module-level import?
#   Using FastAPI's lifespan hook makes the intent explicit: this is a
#   deliberate startup cost, not a side-effect of importing the file.
#   FastAPI waits for the lifespan to yield before it starts accepting
#   requests, so by the time the first /query arrives the pipeline is warm.
#
# What happens inside `from src.rag import answer`:
#   Python imports src/rag.py, which imports src/retrieve.py.
#   retrieve.py has module-level code that:
#     1. loads SentenceTransformer('all-MiniLM-L6-v2')  — ~1-2 s, ~300 MB RAM
#     2. opens the Chroma PersistentClient and loads the HNSW index
#   Both are cached in the module; every subsequent call reuses them at
#   zero re-loading cost.
# ─────────────────────────────────────────────────────────────────────────────

_answer_fn: Callable | None = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    global _answer_fn
    logger.info("Startup — loading RAG pipeline (model + Chroma index) …")
    from src.rag import answer          # triggers one-time model loading
    _answer_fn = answer
    logger.info("RAG pipeline ready.")
    yield
    # No teardown needed: Chroma's PersistentClient closes on garbage collection.


# ─────────────────────────────────────────────────────────────────────────────
# APP
# ─────────────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Breast Cancer RAG API",
    description=(
        "Answers clinical breast-cancer treatment questions grounded in "
        "~2 500 PubMed abstracts. Every claim is cited with a PMID."
    ),
    version="0.5.0",
    lifespan=lifespan,
)


# ─────────────────────────────────────────────────────────────────────────────
# ENDPOINTS
# ─────────────────────────────────────────────────────────────────────────────

@app.get(
    "/health",
    response_model=HealthResponse,
    summary="Liveness check",
    tags=["ops"],
)
def health():
    """Returns `{"status": "ok"}` when the server is running."""
    return HealthResponse(status="ok")


@app.post(
    "/query",
    response_model=QueryResponse,
    summary="Run the RAG pipeline",
    tags=["rag"],
)
def query(body: QueryRequest):
    """
    Retrieves the top-**k** most relevant PubMed abstracts for *question*,
    then asks Gemini to produce a grounded, cited answer.

    - **question**: plain-English clinical question
    - **k**: number of abstracts to retrieve (default 5, max 20)

    Note: this is a plain `def`, not `async def`.  FastAPI automatically runs
    synchronous endpoints in a thread-pool worker, so the blocking Gemini HTTP
    call never stalls the event loop.  Making this `async def` and calling the
    synchronous SDK directly would be wrong — it would block the loop and
    prevent other requests from being served concurrently.
    """
    if _answer_fn is None:
        raise HTTPException(status_code=503, detail="Pipeline not initialised yet.")

    try:
        result = _answer_fn(body.question, body.k)
    except TimeoutError as exc:
        logger.error("Request timed out: %s", exc)
        raise HTTPException(status_code=504, detail=str(exc))
    except RuntimeError as exc:
        logger.error("Pipeline error: %s", exc)
        raise HTTPException(status_code=502, detail=str(exc))
    except Exception as exc:
        logger.error("Unexpected error in /query: %s", exc)
        raise HTTPException(status_code=500, detail="Internal server error.")

    sources = [
        Source(
            pmid=s["pmid"],
            title=s["title"],
            snippet=s.get("snippet", ""),
        )
        for s in result["sources"]
    ]

    return QueryResponse(answer=result["answer"], sources=sources)
